name: Find Linear Issue in Pull Request

env:
  ACTIONS_STEP_DEBUG: true

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: ["opened", "edited", "reopened", "synchronize"]

jobs:
  create-linear-issue-on-pull-request:
    runs-on: ubuntu-latest
    name: A test job
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout action repo
        uses: actions/checkout@v3
      - name: Find the Linear Issue
        id: findIssue
        uses: ./ # Uses an action in the root directory
        with:
          linear-api-key: ${{secrets.LINEAR_API_KEY}}
          linear-issue-label-ids: "ea7fc863-71f7-409c-bcda-b42a22dc9a75,7c8d0d42-b53c-49c4-ba23-b48f6e14eb62,77c37057-9bd9-413b-a8b8-5aabd7c1a557"
      - name: Create comment in PR with Linear Issue link
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            [${{ steps.findIssue.outputs.linear-issue-identifier }}: ${{ steps.findIssue.outputs.linear-issue-title }}](${{ steps.findIssue.outputs.linear-issue-url }})
